name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger deployment when changes are pushed to the main branch

permissions:
  contents: write  # This is important - it gives the workflow permission to write to your repository

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'npm'  # Add caching for faster builds

    - name: Install dependencies
      run: npm ci  # More reliable than npm install for CI environments

    - name: Build project
      run: npm run build  # Assuming this builds to a 'dist' directory

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: dist  # The folder the action should deploy
        branch: gh-pages  # The branch the action should deploy to
        # No need to specify GITHUB_TOKEN as it's automatically available with the permissions above
