name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # This ensures the deployment runs on pushes to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0  # Fetches the full history for all branches
    
    - name: Install dependencies
      run: |
        npm install
        npm run build

    - name: Deploy to GitHub Pages
      run: |
        git config --global user.email "you@example.com"
        git config --global user.name "Your Name"
        git remote add origin https://github.com/${{ github.repository }}.git
        git fetch origin
        git checkout --orphan gh-pages
        git rm -rf .  # Clean up old files on gh-pages
        cp -r dist/* .  # Assuming 'dist' is where your build output is
        git add .
        git commit -m "Deploy to GitHub Pages"
        git push --force origin gh-pages  # Push to gh-pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
